version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - 3306:3306

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: sf4_php
    restart: on-failure
    volumes:
      - ./my_project_name/:/usr/src/app
    user: 1000:1000

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./my_project_name/public/:/usr/src/app
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - php